<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CommonMemberVerifyInfo extends Model
{
    //
    protected $table='pre_common_member_verify_info';

    public function insert(array $values)
    {
        return parent::insert($values); // TODO: Change the autogenerated stub
    }
}
